### ISSUE TITLE
Which repo to use ?

### ISSUE THREAD

**Issue by Alex-PLACET** [forensicmatt/RustyUsn#7]
Hi,
I'm looking for a tool to parse the MFT and I see that RustyUsn and RsWindowsThingies duplicate code which do that. I don't know which one to use, I mean which one will be deprecated or kept up to date.

**Comment by forensicmatt** [comment]
RustyUsn is for parsing the USN Journal offline and RsWindowsThingies has the tool that uses the windows API to watch the USN journal live. This repo does have a tool that that watches it live, but I am depreciating that tool in this repo.

But if you are looking for an MFT tool, I recommend https://github.com/omerbenamram/mft. Though its more of a library and less of a complete tool.

**Comment by Alex-PLACET** [comment]
@forensicmatt I want to list files from a live mft, it seems that https://github.com/omerbenamram/mft is not able to do that because it doesn't use winapi.

**Comment by forensicmatt** [comment]
Ah, I dont have any tools that do that. If you need an example of how to call the Windows API to fetch a record you can see it here: https://github.com/forensicmatt/RsWindowsThingies/blob/d3a0e033381e4c6208bcd2d88a695e0fbf29ae31/src/file/helper.rs#L59

Just remember it can't get unallocated and it just grabs the raw entry meaning no mft entry fragmentation is accounted for. Also, the fixup array is already applied.

https://docs.microsoft.com/en-us/windows/win32/api/winioctl/ni-winioctl-fsctl_get_ntfs_file_record#remarks
